spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: false

    show-sql: true
  sql:
    init:
      mode: never


logging:
  level:
    ROOT: ERROR