app:
  title: Ebook Library
  version: 0.1
  dao:
    localeProvider:
      lang: en
spring:
  datasource:
    url: jdbc:h2:mem:home5db
  messages:
    basename: i18n/messages
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
#debug: true
